#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mdev -s

cat <<!


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

        _       _     __ _
  /\/\ (_)_ __ (_)   / /(_)_ __  _   ___  __
 /    \| | '_ \| |  / / | | '_ \| | | \ \/ /
/ /\/\ \ | | | | | / /__| | | | | |_| |>  <
\/    \/_|_| |_|_| \____/_|_| |_|\__,_/_/\_

Welcome to mini_linux


!

ip link set eth0 up
udhcpc -i eth0 -s /etc/dhcp.script

if [[ "`cat /proc/cmdline`" =~ "virtplat_rootfs=ubuntu" ]]
then
  mkdir /dev/pts
  mount -t devpts none /dev/pts
  mount -t debugfs debugfs /sys/kernel/debug
  mount -t securityfs securityfs /sys/kernel/security

  mkdir -p /mnt/ubuntu
  mount /dev/sda1 /mnt/ubuntu

  mount -t proc /proc /mnt/ubuntu/proc
  mount --rbind /sys /mnt/ubuntu/sys
  mount --rbind /dev /mnt/ubuntu/dev

  rm /dev/null
  mknod -m 0666 /dev/null c 1 3

  chroot /mnt/ubuntu /bin/bash
else
  exec /bin/sh
fi
